// Neural bandwidth extension: the DSP half (upsampler, mel frontend, iSTFT,
// crossover merge) is pure math verified here against reference values from
// the original NumPy implementation — the mel fixture in tests/fixtures/ was
// generated by running LavaSR-ONNX's exact frontend over the same chirp. The
// keystone test then runs the real fp16 ONNX models (from public/bwe/)
// through onnxruntime-web's wasm backend on a genuine Codec 2 decode, the
// same engine the browser uses.

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  BWE_SAMPLE_RATE,
  bweEnhance,
  createBweRuntime,
  istftSame,
  lr4Merge,
  melSpectrogram,
  upsampleTo48k,
} from '../src/lib/bwe';
import { irfft, rfft } from '../src/lib/fft';
import { codec2Decode, codec2Encode } from '../src/lib/codec2';
import { decimate2 } from '../src/lib/resample';

/** Same deterministic chirp as scratch fixture generation: 300→? Hz linear
 * chirp plus a 1 kHz tone, 2 s at 48 kHz, computed in float64. */
function chirp(): Float32Array {
  const n = 96000;
  const x = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    const t = i / 48000;
    x[i] = 0.5 * Math.sin(2 * Math.PI * (300 * t + 875 * t * t)) + 0.2 * Math.sin(2 * Math.PI * 1000 * t);
  }
  return x;
}

function goertzelDb(x: Float32Array, sampleRate: number, hz: number): number {
  const w = (2 * Math.PI * hz) / sampleRate;
  const coeff = 2 * Math.cos(w);
  let s1 = 0, s2 = 0;
  for (let i = 0; i < x.length; i++) {
    const s0 = x[i]! + coeff * s1 - s2;
    s2 = s1;
    s1 = s0;
  }
  return 10 * Math.log10((s1 * s1 + s2 * s2 - coeff * s1 * s2) / x.length + 1e-20);
}

describe('fft', () => {
  it('matches the analytic DFT of a sine and round-trips', () => {
    const n = 2048;
    const x = new Float64Array(n);
    for (let i = 0; i < n; i++) x[i] = Math.sin((2 * Math.PI * 32 * i) / n);
    const spec = rfft(x, n);
    // bin 32 should hold magnitude n/2, all others ~0
    expect(Math.hypot(spec.re[32]!, spec.im[32]!)).toBeCloseTo(n / 2, 6);
    expect(Math.hypot(spec.re[100]!, spec.im[100]!)).toBeLessThan(1e-6);
    const back = irfft(spec, n);
    for (let i = 0; i < n; i += 97) expect(back[i]!).toBeCloseTo(x[i]!, 10);
  });
});

describe('upsampleTo48k', () => {
  it('interpolates 8 kHz to 48 kHz preserving in-band tones', () => {
    const rate = 8000;
    const pcm = new Int16Array(rate); // 1 s
    for (let i = 0; i < pcm.length; i++) {
      pcm[i] = Math.round(12000 * Math.sin((2 * Math.PI * 1000 * i) / rate));
    }
    const out = upsampleTo48k(pcm, rate);
    expect(out.length).toBe(pcm.length * 6);
    const tone = goertzelDb(out, 48000, 1000);
    // Images of the 1 kHz tone under 6× zero-stuffing would land at 7, 9 kHz…
    expect(tone - goertzelDb(out, 48000, 7000)).toBeGreaterThan(50);
    expect(tone - goertzelDb(out, 48000, 9000)).toBeGreaterThan(50);
    // Passband level preserved (tone RMS ≈ 12000/32768/√2)
    let rms = 0;
    for (let i = 0; i < out.length; i++) rms += out[i]! * out[i]!;
    rms = Math.sqrt(rms / out.length);
    expect(rms).toBeCloseTo((12000 / 32768) * Math.SQRT1_2, 2);
  });

  it('rejects non-integer factors', () => {
    expect(() => upsampleTo48k(new Int16Array(100), 44100)).toThrow();
  });
});

describe('melSpectrogram', () => {
  it('matches the reference NumPy frontend on the chirp fixture', () => {
    const meta = JSON.parse(readFileSync('tests/fixtures/bwe-chirp-mel.json', 'utf8')) as {
      nMels: number;
      frames: number;
    };
    const ref = new Float32Array(readFileSync('tests/fixtures/bwe-chirp-mel.f32').buffer.slice(0));
    const { mel, frames } = melSpectrogram(chirp());
    expect(frames).toBe(meta.frames);
    expect(mel.length).toBe(ref.length);
    let maxDiff = 0;
    let sumDiff = 0;
    for (let i = 0; i < mel.length; i++) {
      const d = Math.abs(mel[i]! - ref[i]!);
      if (d > maxDiff) maxDiff = d;
      sumDiff += d;
    }
    expect(maxDiff).toBeLessThan(0.02); // log-mel units
    expect(sumDiff / mel.length).toBeLessThan(1e-3);
  });
});

describe('istftSame', () => {
  it('reconstructs the chirp from its own STFT frames', () => {
    // Frame exactly like the pipeline (padding='same', periodic hann, hop 512)
    const x = chirp();
    const nFft = 2048;
    const hop = 512;
    const pad = (nFft - hop) / 2;
    const padded = new Float64Array(x.length + 2 * pad);
    for (let i = 0; i < x.length; i++) padded[pad + i] = x[i]!;
    for (let i = 0; i < pad; i++) {
      padded[i] = x[pad - i]!;
      padded[pad + x.length + i] = x[x.length - 2 - i]!;
    }
    const window = new Float64Array(nFft);
    for (let i = 0; i < nFft; i++) window[i] = 0.5 - 0.5 * Math.cos((2 * Math.PI * i) / nFft);
    const frames = Math.floor((padded.length - nFft) / hop) + 1;
    const bins = nFft / 2 + 1;
    const real = new Float32Array(bins * frames);
    const imag = new Float32Array(bins * frames);
    const frame = new Float64Array(nFft);
    for (let t = 0; t < frames; t++) {
      for (let i = 0; i < nFft; i++) frame[i] = padded[t * hop + i]! * window[i]!;
      const spec = rfft(frame, nFft);
      for (let f = 0; f < bins; f++) {
        real[f * frames + t] = spec.re[f]!;
        imag[f * frames + t] = spec.im[f]!;
      }
    }
    const back = istftSame(real, imag, frames, x.length);
    expect(back.length).toBe(x.length);
    for (let i = 0; i < x.length; i += 501) {
      expect(Math.abs(back[i]! - x[i]!)).toBeLessThan(1e-3);
    }
  });
});

describe('lr4Merge', () => {
  it('keeps the original below the crossover and the enhanced above', () => {
    const n = 48000;
    const original = new Float32Array(n);
    const enhanced = new Float32Array(n);
    for (let i = 0; i < n; i++) {
      const t = i / 48000;
      original[i] = 0.5 * Math.sin(2 * Math.PI * 1000 * t) + 0.5 * Math.sin(2 * Math.PI * 6000 * t);
      enhanced[i] = 0.5 * Math.sin(2 * Math.PI * 1100 * t) + 0.5 * Math.sin(2 * Math.PI * 6600 * t);
    }
    const out = lr4Merge(enhanced, original);
    const level = (hz: number): number => goertzelDb(out, 48000, hz);
    // Original's low tone and enhanced's high tone pass (≈ -12 dB for 0.5 amp)
    expect(level(1000)).toBeGreaterThan(-14);
    expect(level(6600)).toBeGreaterThan(-14);
    // The unwanted bands are attenuated: LR4 is 24 dB/oct, so the original's
    // 6 kHz tone (0.74 oct above the 3.6 kHz crossover) drops ~18 dB and the
    // enhanced's 1.1 kHz tone (1.7 oct below) drops ~40 dB.
    expect(level(6000)).toBeLessThan(level(6600) - 15);
    expect(level(1100)).toBeLessThan(level(1000) - 30);
  });
});

describe('neural BWE end-to-end (real models, wasm)', () => {
  it('synthesizes the missing high band on a real Codec 2 decode', async () => {
    // Wideband-ish synth → decimate → Codec 2 1600 round-trip, then enhance.
    const rate = 16000;
    const seconds = 4;
    const wide = new Int16Array(rate * seconds);
    let phase = 0;
    for (let i = 0; i < wide.length; i++) {
      const t = i / rate;
      const f0 = 130 + 40 * Math.sin(2 * Math.PI * 0.7 * t);
      phase += (2 * Math.PI * f0) / rate;
      let v = 0;
      for (let k = 1; k * f0 < 3800; k++) v += Math.sin(k * phase) / (1 + k * 0.5);
      const envelope = Math.max(0, Math.sin(2 * Math.PI * 2.1 * t)) ** 0.7;
      wide[i] = Math.max(-32768, Math.min(32767, Math.round(v * envelope * 9000)));
    }
    const narrow = decimate2(wide);
    const bits = await codec2Encode('1600', narrow);
    const decoded = await codec2Decode('1600', bits);

    const ort = await import('onnxruntime-web');
    ort.env.wasm.numThreads = 1;
    const rt = await createBweRuntime(
      ort,
      new Uint8Array(readFileSync('public/bwe/enhancer-backbone-fp16.onnx')),
      new Uint8Array(readFileSync('public/bwe/enhancer-spec-head-fp16.onnx')),
    );
    const out = await bweEnhance(rt, decoded, 8000);
    expect(out.length).toBe(decoded.length * 6);

    const outF = new Float32Array(out.length);
    let peak = 0;
    for (let i = 0; i < out.length; i++) {
      outF[i] = out[i]! / 32768;
      peak = Math.max(peak, Math.abs(outF[i]!));
    }
    expect(peak).toBeLessThanOrEqual(0.9851);

    const baseline = upsampleTo48k(decoded, 8000);
    const bandDb = (x: Float32Array, hz: number): number => goertzelDb(x, BWE_SAMPLE_RATE, hz);
    // The model must add real energy where the 8 kHz decode has none…
    let gained = 0;
    for (const hz of [4500, 5000, 5500, 6000, 6500]) {
      gained += bandDb(outF, hz) - bandDb(baseline, hz);
    }
    expect(gained / 5).toBeGreaterThan(12);
    // …while the authentic low band passes through the crossover unharmed.
    for (const hz of [500, 1000, 2000]) {
      expect(Math.abs(bandDb(outF, hz) - bandDb(baseline, hz))).toBeLessThan(1.5);
    }
  }, 60_000);
});
